apiVersion: v1
kind: Secret
metadata:
  name: coupon-service-secret
  namespace: eg58sj-dev
  labels:
    app.kubernetes.io/name: coupon-service
    app.kubernetes.io/part-of: coupon-service
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
  SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
