apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: eg58sj-dev
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: coupon-service
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
