apiVersion: v1
kind: ConfigMap
metadata:
  name: coupon-service-config
  namespace: eg58sj-dev
  labels:
    app.kubernetes.io/name: coupon-service
    app.kubernetes.io/part-of: coupon-service
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/coupon_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
  SPRINGDOC_ENABLED: "false"
