apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: eg58sj-dev
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: coupon-service
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  MYSQL_DATABASE: "coupon_db"
  MYSQL_USER: "${MYSQL_USER}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
